### ISSUE TITLE
AssemblyScript: --memoryBase flag

### ISSUE THREAD

**Issue by LeXXik** [torch2424/wasm-by-example#103]
Starting from the `WebAssembly Linear Memory` example, the paragraph keeps telling to go and look at `--memoryBase` flag. And that's all.

It would be nice, if there would be a few words about how to actually use it. The examples don't use this flag, then why should I? Will I get unexpected results, if yes, then when? For example, the instruction here:
https://github.com/torch2424/wasm-by-example/tree/master/examples/webassembly-linear-memory/demo/assemblyscript
says to use the following command to compile `asc index.ts -b index.wasm -t index.wat`

**Comment by torch2424** [comment]
Ah! I didn't realize that! Thanks for mentioning this @LeXXik ! 

I think I wrote that originally, and then forgot to link to the flag in the docs :upside_down_face: So I'll fix this asap :smile:
