### ISSUE TITLE
Hello World example can be misleading

### ISSUE THREAD

**Issue by nepp2** [torch2424/wasm-by-example#108]
Hey. I like your website. It is much simpler and easier to follow than the other wasm tutorials I've found. However, there is one detail that led me astray for quite a while (particularly as someone who is unfamiliar with modern JS.)

The example on [this page](https://wasmbyexample.dev/examples/hello-world/hello-world.rust.en-us.html) calls `add` directly on the wasm object returned by the `init` function, but this bypasses the bindings generated by wasm-bindgen. It still works in the case of `add` because the bindings don't need to do anything clever. However, if functions with more complex signatures are added to the example (e.g. functions with string arguments), they won't work. For example:

```
  const helloWorld = await init("./pkg/hello_world_bg.wasm");

  // Call the Add function export from wasm, save the result
  const addResult = helloWorld.add(24, 24);

  // Extend the example with a string concatenation function
  const concatResult = helloWorld.concat("Hello ", "world");

  console.log(concatResult); // prints an empty string
```

The correct way of importing more complex functions is demonstrated [later](
https://wasmbyexample.dev/examples/passing-high-level-data-types-with-wasm-bindgen/passing-high-level-data-types-with-wasm-bindgen.rust.en-us.html), but it's easy to miss this distinction when you don't expect it and don't know how ES6 imports work. I actually assumed these syntaxes meant the same thing, and JavaScript just quietly does the wrong thing without throwing an exception. I think it would be helpful if the first example called `add` via the generated bindings, as this seems like it is always the better default.

This is a small detail, but it was enough to trip me up, and I found at least [one other post online](https://stackoverflow.com/questions/61986932/how-to-pass-a-string-from-js-to-wasm-generated-through-rust-using-wasm-bindgen-w) from someone who made the same mistake.

**Comment by torch2424** [comment]
Hello! Ah thanks for calling this out @nepp2 ! :) 

Oh yeah I wrote that Rust example when I was still learning rust/wasm myself. I had some rust folks look it over, but I guess we all missed it when I first published this, and you are completely correct. I am (unintentionally ) suttle-y skipping past the generated glue code. :upside_down_face: 

For the sake of the example, I'd still want users to touch the direct wasm, so the API "behind the scenes" is clear. But I'll make that more apparent that is what we are doing! :smile: Thanks for bringing this up!
