### ISSUE TITLE
Example Redirects not working

### ISSUE THREAD

**Issue by davidnuon** [torch2424/wasm-by-example#12]
In the bottom of each of the generated example pages, there's a link that goes to the next example in the list that looks like this: 

`https://wasmbyexample.dev/example-redirect?exampleName=graphics`

When a user clicks on it, it leads to a 404.

However, the following does work: 

`https://wasmbyexample.dev/example-redirect.html?exampleName=graphics`

Maybe a typo or some rewrite rules not working?

**Comment by torch2424** [comment]
@davidnuon Thank you for finding a bug on my secret project I'm not "launching" till tommorrow haha :smile: :joy: 

Going to fix this now actually! :tada:

**Comment by davidnuon** [comment]
I'll keep my eyes 👀 on this.

**Comment by torch2424** [comment]
It's lit! :fire: Fixed with https://github.com/torch2424/devops/commit/b15b1b2f2ca767d1cfdeafd07e4169154fb85a80 :smile:
