### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by timscodebase** [torch2424/wasm-by-example#135]
Steps to replicate

1. Navigate to https://wasmbyexample.dev/examples/reading-and-writing-audio/reading-and-writing-audio.rust.en-us.html
2. At the very bottom there is a [strings](https://wasmbyexample.dev/example-redirect?exampleName=strings) link.
3. Click it and you will be taken to a Netlify Error page
![Screen Shot 2022-01-08 at 6 42 19 PM](https://user-images.githubusercontent.com/69870077/148667165-1f771ac7-1228-4e3c-8f51-da8b4135e345.png)

**Comment by torch2424** [comment]
Ah! Thank you for finding this bug! 😄 Looking into this, seems like I forgot to update this sentence. We went ahead and changed the strings example to various different names per each language. I'll go ahead and open a PR for this! 🎉
