### ISSUE TITLE
Broken link in assemblyscript

### ISSUE THREAD

**Issue by Albertoimpl** [torch2424/wasm-by-example#138]
Hello! First of all, I would like to thank you for putting all these resources together.

I found that there is a broken link in https://github.com/torch2424/wasm-by-example/blob/master/examples/hello-world/hello-world.assemblyscript.en-us.md?plain=1#L26 
I was tempted to submit a PR to redirect to https://www.assemblyscript.org/compiler.html#using-the-compiler however, I could not find any installation instructions for it, and `npm install -g asc` does not install any executable.
Do you have any suggestions?

Thanks!

**Comment by torch2424** [comment]
@Albertoimpl Thanks for opening an issue, and letting me know about the broken link! 😄 

Definitely, so are you asking how to install the assemblyscript compiler? Or how to install this project?

To install the assemblyscript compiler, I'm pretty sure you need to use:

`npm install -g assemblyscript`

and to install and run this project, you can see the [building & running instructions here on the README](https://github.com/torch2424/wasm-by-example#building--running-the-project).

Thanks! 😄

**Comment by Albertoimpl** [comment]
Thank you so much for the response @torch2424, it was `npm install -g assemblyscript` that I was not able to find anywhere! I was using `npm install -g asc` and `npm install -g asc-cli` unsuccessfully.

I created a PR to document this and to update the link to the docs: https://github.com/torch2424/wasm-by-example/pull/140

**Comment by torch2424** [comment]
@Albertoimpl Glad I could help! 😄 And thank you SOOOO much for turning this into a PR to improve the docs! I super appreciate that! Closing this since I merged the PR 😄 🎉

**Comment by Albertoimpl** [comment]
No problem! Thank you again for the great content!
