### ISSUE TITLE
Fix typo on rust samples

### ISSUE THREAD

**Issue by torch2424** [torch2424/wasm-by-example#35]
At the top of the samples they say: `// Add the wasm-pack crate`. We should say something like: `// Add the wasm-pack/wasm-bindgen crate`. As it is actually wasm-bindgen

**Comment by sendilkumarn** [comment]
Actually it should be just `//Import the wasm-bindgen crate`

**Comment by torch2424** [comment]
@sendilkumarn Ah yes, I agree.

The reason why I said: `// Add the wasm-pack/wasm-bindgen crate` was to hopefully imply the relationship between the two. But the wording can definitely be better 😄

**Comment by torch2424** [comment]
closed by #38 Thank you @sendilkumarn :smile:
