### ISSUE TITLE
Add Go examples 

### ISSUE THREAD

**Issue by sendilkumarn** [torch2424/wasm-by-example#37]
It would be great to add Go examples and also show them how to do it for both the normal Go compiler and `TinyGo` compiler

**Comment by torch2424** [comment]
+1 Would be great to have this 😄 👍 

Let's definitely keep this on the roadmap, and for @sendilkumarn or anyone else with Go/Wasm experience. More than welcome to open some PRs 😄

**Comment by sendilkumarn** [comment]
can you assign it to me? I will work on it 👍

**Comment by torch2424** [comment]
Totally! Thank you! @sendilkumarn 😄

**Comment by torch2424** [comment]
Hello @sendilkumarn ! :smile: So I was going to start this soon. I was thinking of just doing TinyGo, as it seems like the best practice way to do Go and Wasm currently. You have any thoughts on this? :smile:

**Comment by sendilkumarn** [comment]
oh gosh!! How did I miss this thing? I'm so sorry. 

I will definitely do it with tinygo.. It is awesome and creates tiny binaries. But having an official version side by side is also good.

**Comment by torch2424** [comment]
@sendilkumarn No worries at all!

Personally I've been super busy as of lately, so I haven't had much open source time so I understand 😀

And awesome! I'm thinking I'll do something similar to Emscripten, and make the Go labeled as "TinyGo(Go)", and we can always add official go compiler examples if that ever improves! Thanks for the input! 😀🎉
