### ISSUE TITLE
Change some of the new colors.

### ISSUE THREAD

**Issue by torch2424** [torch2424/wasm-by-example#50]
So after showing people the awesome new design changes by @eduardogoncalves I got some feedback that I agree with:

1. For the inline code snippets, 

![Screen Shot 2019-08-14 at 9 49 46 AM](https://user-images.githubusercontent.com/1448289/63039805-f064c680-be78-11e9-8c08-0f58d8a3f028.png)

I think it would be good to have a small light gray border, and a slightly darker purple background 😄 

2. For hovering over links, I think if the link hover color was lighter, it would be easier to read / see, and look nice 😄 

Let me know what you think @eduardogoncalves 😄 I can do this really quick if you don't have the bandwidth 👍

**Comment by eduardogoncalves** [comment]
ty 😆
@torch2424  If you don't mind, you can change it ☺️

**Comment by torch2424** [comment]
Awesome! I totally will :smile:
