### ISSUE TITLE
how to use class in assemblyScript

### ISSUE THREAD

**Issue by nokisnojok** [torch2424/wasm-by-example#56]

**Comment by torch2424** [comment]
Hello!

So normally I would say check out the [AssemblyScript Docuementation](https://docs.assemblyscript.org/) for more syntax specific examples, but there isn't very many docs on classes 😂 

So here are some other examples that should get you going:

* [Static classes if you are just looking for organization](https://github.com/AssemblyScript/assemblyscript/blob/master/tests/compiler/class-static-function.ts)

* [Instance classes if you want to create multiple instances or do some general Object orientated programming](https://docs.assemblyscript.org/basics/limitations#oop)

Hope that helps! 😄 I will keep this issue open for Wasm By Example, as we should show this off in a section.

cc @MaxGraey @dcodeIO

**Comment by dcodeIO** [comment]
One thing to note is that classes have [a set of limitations](https://docs.assemblyscript.org/basics/limitations#oop) currently, but unless one wants interfaces or virtual members, it's usable.
